import 'currency_rates.dart';

enum UnitStrategy { factor, reciprocal, formula }
class UnitDef {
  const UnitDef({required this.id, required this.name, required this.symbol, required this.strategy, this.factor = 1});
  final String id, name, symbol;
  final UnitStrategy strategy;
  final double factor;
}
class CategoryDef {
  const CategoryDef({required this.id, required this.name, required this.units, this.isStringBased = false});
  final String id, name;
  final List<UnitDef> units;
  final bool isStringBased;
}
class UnitDefinitions {
  static List<CategoryDef> get categories => [
    CategoryDef(id: 'currency', name: 'Currency', units: CurrencyRates.units),
    CategoryDef(id: 'length', name: 'Length', isStringBased: false, units: [
      UnitDef(id: 'meters', name: 'Meters', symbol: 'm', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'feet', name: 'Feet', symbol: 'ft', strategy: UnitStrategy.factor, factor: 0.3048),
      UnitDef(id: 'yards', name: 'Yards', symbol: 'yd', strategy: UnitStrategy.factor, factor: 0.9144),
      UnitDef(id: 'kilometers', name: 'Kilometers', symbol: 'km', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'miles', name: 'Miles', symbol: 'mi', strategy: UnitStrategy.factor, factor: 1609.344),
      UnitDef(id: 'nautical_miles', name: 'Nautical Miles', symbol: 'nmi', strategy: UnitStrategy.factor, factor: 1852.0),
      UnitDef(id: 'centimeters', name: 'Centimeters', symbol: 'cm', strategy: UnitStrategy.factor, factor: 0.01),
      UnitDef(id: 'inches', name: 'Inches', symbol: 'in', strategy: UnitStrategy.factor, factor: 0.0254),
      UnitDef(id: 'mils', name: 'Mils', symbol: 'mil', strategy: UnitStrategy.factor, factor: 0.0000254),
      UnitDef(id: 'millimeters', name: 'Millimeters', symbol: 'mm', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'micrometers', name: 'Micrometers', symbol: 'µm', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'nanometers', name: 'Nanometers', symbol: 'nm', strategy: UnitStrategy.factor, factor: 1e-9),
      UnitDef(id: 'angstroms', name: 'Angstroms', symbol: 'Å', strategy: UnitStrategy.factor, factor: 1e-10),
      UnitDef(id: 'picometers', name: 'Picometers', symbol: 'pm', strategy: UnitStrategy.factor, factor: 1e-12),
      UnitDef(id: 'feet_us', name: 'Feet (US Survey)', symbol: 'ft (US)', strategy: UnitStrategy.factor, factor: 0.3048006),
      UnitDef(id: 'astronomical_units', name: 'Astronomical Units', symbol: 'AU', strategy: UnitStrategy.factor, factor: 1.495978707e11),
      UnitDef(id: 'light_years', name: 'Light Years', symbol: 'ly', strategy: UnitStrategy.factor, factor: 9.4607304725808e15),
      UnitDef(id: 'parsec', name: 'Parsec', symbol: 'pc', strategy: UnitStrategy.factor, factor: 3.0856775814913673e16),
    ]),
    CategoryDef(id: 'area', name: 'Area', isStringBased: false, units: [
      UnitDef(id: 'square_meters', name: 'Square Meters', symbol: 'm²', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'square_feet', name: 'Square Feet', symbol: 'ft²', strategy: UnitStrategy.factor, factor: 0.092903),
      UnitDef(id: 'square_yard', name: 'Square Yard', symbol: 'yd²', strategy: UnitStrategy.factor, factor: 0.836127),
      UnitDef(id: 'hectares', name: 'Hectares', symbol: 'ha', strategy: UnitStrategy.factor, factor: 10000.0),
      UnitDef(id: 'acres', name: 'Acres', symbol: 'ac', strategy: UnitStrategy.factor, factor: 4046.86),
      UnitDef(id: 'square_kilometers', name: 'Square Kilometers', symbol: 'km²', strategy: UnitStrategy.factor, factor: 1e6),
      UnitDef(id: 'square_miles', name: 'Square Miles', symbol: 'mi²', strategy: UnitStrategy.factor, factor: 2589988.110336),
      UnitDef(id: 'square_centimeters', name: 'Square Centimeters', symbol: 'cm²', strategy: UnitStrategy.factor, factor: 0.0001),
      UnitDef(id: 'square_millimeters', name: 'Square Millimeters', symbol: 'mm²', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'square_inches', name: 'Square Inches', symbol: 'in²', strategy: UnitStrategy.factor, factor: 0.00064516),
      UnitDef(id: 'are', name: 'Are', symbol: 'a', strategy: UnitStrategy.factor, factor: 100.0),
      UnitDef(id: 'square_feet_us', name: 'Square Feet (US Survey)', symbol: 'ft² (US)', strategy: UnitStrategy.factor, factor: 0.092903411613474),
    ]),
    CategoryDef(id: 'volume', name: 'Volume', isStringBased: false, units: [
      UnitDef(id: 'cubic_meters', name: 'Cubic Meters', symbol: 'm³', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'liters', name: 'Liters', symbol: 'L', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'us_gallons', name: 'US Gallons', symbol: 'gal (US)', strategy: UnitStrategy.factor, factor: 3.78541),
      UnitDef(id: 'imperial_gallons', name: 'Imperial Gallons', symbol: 'gal (UK)', strategy: UnitStrategy.factor, factor: 4.54609),
      UnitDef(id: 'us_pints', name: 'US Pints', symbol: 'pt (US)', strategy: UnitStrategy.factor, factor: 0.473176),
      UnitDef(id: 'imperial_pints', name: 'Imperial Pints', symbol: 'pt (UK)', strategy: UnitStrategy.factor, factor: 0.568261),
      UnitDef(id: 'us_quarts', name: 'US Quarts', symbol: 'qt (US)', strategy: UnitStrategy.factor, factor: 0.946353),
      UnitDef(id: 'deciliters', name: 'Deciliters', symbol: 'dL', strategy: UnitStrategy.factor, factor: 0.1),
      UnitDef(id: 'centiliters', name: 'Centiliters', symbol: 'cL', strategy: UnitStrategy.factor, factor: 0.01),
      UnitDef(id: 'milliliters', name: 'Milliliters', symbol: 'mL', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'microliters', name: 'Microliters', symbol: 'µL', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'tablespoons_us', name: 'Tablespoons (US)', symbol: 'tbsp', strategy: UnitStrategy.factor, factor: 0.0147868),
      UnitDef(id: 'australian_tablespoons', name: 'Australian Tablespoons', symbol: 'tbsp (AU)', strategy: UnitStrategy.factor, factor: 0.02),
      UnitDef(id: 'teaspoons_us', name: 'Teaspoons (US)', symbol: 'tsp', strategy: UnitStrategy.factor, factor: 0.00492892),
      UnitDef(id: 'teaspoons_metric', name: 'Teaspoons (Metric)', symbol: 'tsp (met)', strategy: UnitStrategy.factor, factor: 0.005),
      UnitDef(id: 'cups', name: 'Cups', symbol: 'cup', strategy: UnitStrategy.factor, factor: 0.236588),
      UnitDef(id: 'cubic_millimeters', name: 'Cubic Millimeters', symbol: 'mm³', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'cubic_centimeters', name: 'Cubic Centimeters', symbol: 'cm³', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'cubic_inches', name: 'Cubic Inches', symbol: 'in³', strategy: UnitStrategy.factor, factor: 0.0163871),
      UnitDef(id: 'cubic_feet', name: 'Cubic Feet', symbol: 'ft³', strategy: UnitStrategy.factor, factor: 28.3168),
      UnitDef(id: 'us_fluid_ounces', name: 'US Fluid Ounces', symbol: 'fl oz (US)', strategy: UnitStrategy.factor, factor: 0.0295735),
      UnitDef(id: 'imperial_fluid_ounces', name: 'Imperial Fluid Ounces', symbol: 'fl oz (UK)', strategy: UnitStrategy.factor, factor: 0.0284131),
      UnitDef(id: 'us_gill', name: 'US Gill', symbol: 'gi (US)', strategy: UnitStrategy.factor, factor: 0.118294),
      UnitDef(id: 'imperial_gill', name: 'Imperial Gill', symbol: 'gi (UK)', strategy: UnitStrategy.factor, factor: 0.142065),
    ]),
    CategoryDef(id: 'mass', name: 'Mass', isStringBased: false, units: [
      UnitDef(id: 'kilograms', name: 'Kilograms', symbol: 'kg', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'pounds', name: 'Pounds', symbol: 'lb', strategy: UnitStrategy.factor, factor: 0.453592),
      UnitDef(id: 'ounces', name: 'Ounces', symbol: 'oz', strategy: UnitStrategy.factor, factor: 0.0283495),
      UnitDef(id: 'tonnes', name: 'Tonnes', symbol: 't', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'grams', name: 'Grams', symbol: 'g', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'ettograms', name: 'Ettograms', symbol: 'hg', strategy: UnitStrategy.factor, factor: 0.1),
      UnitDef(id: 'centigrams', name: 'Centigrams', symbol: 'cg', strategy: UnitStrategy.factor, factor: 1e-5),
      UnitDef(id: 'milligrams', name: 'Milligrams', symbol: 'mg', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'carats', name: 'Carats', symbol: 'ct', strategy: UnitStrategy.factor, factor: 0.0002),
      UnitDef(id: 'quintals', name: 'Quintals', symbol: 'q', strategy: UnitStrategy.factor, factor: 100.0),
      UnitDef(id: 'pennyweights', name: 'Pennyweights', symbol: 'dwt', strategy: UnitStrategy.factor, factor: 0.00155517),
      UnitDef(id: 'troy_ounces', name: 'Troy Ounces', symbol: 'oz t', strategy: UnitStrategy.factor, factor: 0.0311035),
      UnitDef(id: 'uma', name: 'Unified Atomic Mass', symbol: 'u', strategy: UnitStrategy.factor, factor: 1.66053906660e-27),
      UnitDef(id: 'stones', name: 'Stones', symbol: 'st', strategy: UnitStrategy.factor, factor: 6.35029),
    ]),
    CategoryDef(id: 'time', name: 'Time', isStringBased: false, units: [
      UnitDef(id: 'seconds', name: 'Seconds', symbol: 's', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'minutes_time', name: 'Minutes', symbol: 'min', strategy: UnitStrategy.factor, factor: 60.0),
      UnitDef(id: 'hours', name: 'Hours', symbol: 'h', strategy: UnitStrategy.factor, factor: 3600.0),
      UnitDef(id: 'days', name: 'Days', symbol: 'd', strategy: UnitStrategy.factor, factor: 86400.0),
      UnitDef(id: 'weeks', name: 'Weeks', symbol: 'wk', strategy: UnitStrategy.factor, factor: 604800.0),
      UnitDef(id: 'years_365', name: 'Years (365 days)', symbol: 'yr', strategy: UnitStrategy.factor, factor: 31536000.0),
      UnitDef(id: 'lustrum', name: 'Lustrum (5 yr)', symbol: '5yr', strategy: UnitStrategy.factor, factor: 157680000.0),
      UnitDef(id: 'decades', name: 'Decades', symbol: 'dec', strategy: UnitStrategy.factor, factor: 315360000.0),
      UnitDef(id: 'centuries', name: 'Centuries', symbol: 'c', strategy: UnitStrategy.factor, factor: 3153600000.0),
      UnitDef(id: 'millennium', name: 'Millennium', symbol: 'ka', strategy: UnitStrategy.factor, factor: 31536000000.0),
      UnitDef(id: 'deciseconds', name: 'Deciseconds', symbol: 'ds', strategy: UnitStrategy.factor, factor: 0.1),
      UnitDef(id: 'centiseconds', name: 'Centiseconds', symbol: 'cs', strategy: UnitStrategy.factor, factor: 0.01),
      UnitDef(id: 'milliseconds', name: 'Milliseconds', symbol: 'ms', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'microseconds', name: 'Microseconds', symbol: 'µs', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'nanoseconds', name: 'Nanoseconds', symbol: 'ns', strategy: UnitStrategy.factor, factor: 1e-9),
    ]),
    CategoryDef(id: 'speed', name: 'Speed', isStringBased: false, units: [
      UnitDef(id: 'kilometers_per_hour', name: 'Kilometers per Hour', symbol: 'km/h', strategy: UnitStrategy.factor, factor: 0.277778),
      UnitDef(id: 'miles_per_hour', name: 'Miles per Hour', symbol: 'mph', strategy: UnitStrategy.factor, factor: 0.44704),
      UnitDef(id: 'meters_per_second', name: 'Meters per Second', symbol: 'm/s', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'feets_per_second', name: 'Feet per Second', symbol: 'ft/s', strategy: UnitStrategy.factor, factor: 0.3048),
      UnitDef(id: 'knots', name: 'Knots', symbol: 'kn', strategy: UnitStrategy.factor, factor: 0.514444),
      UnitDef(id: 'minutes_per_kilometer', name: 'Minutes per Kilometer', symbol: 'min/km', strategy: UnitStrategy.reciprocal, factor: 1000.0 / 60.0),
      UnitDef(id: 'minutes_per_mile', name: 'Minutes per Mile', symbol: 'min/mi', strategy: UnitStrategy.reciprocal, factor: 1609.344 / 60.0),
      UnitDef(id: 'speed_of_light', name: 'Speed of Light', symbol: 'c', strategy: UnitStrategy.factor, factor: 299792458.0),
    ]),
    CategoryDef(id: 'force', name: 'Force', isStringBased: false, units: [
      UnitDef(id: 'newton', name: 'Newton', symbol: 'N', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'kilogram_force', name: 'Kilogram-force', symbol: 'kgf', strategy: UnitStrategy.factor, factor: 9.80665),
      UnitDef(id: 'pound_force', name: 'Pound-force', symbol: 'lbf', strategy: UnitStrategy.factor, factor: 4.44822),
      UnitDef(id: 'dyne', name: 'Dyne', symbol: 'dyn', strategy: UnitStrategy.factor, factor: 1e-5),
      UnitDef(id: 'poundal', name: 'Poundal', symbol: 'pdl', strategy: UnitStrategy.factor, factor: 0.138255),
    ]),
    CategoryDef(id: 'fuel_consumption', name: 'Fuel Consumption', isStringBased: false, units: [
      UnitDef(id: 'kilometers_per_liter', name: 'Kilometers per Liter', symbol: 'km/L', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'liters_per_100km', name: 'Liters per 100 km', symbol: 'L/100km', strategy: UnitStrategy.reciprocal, factor: 100.0),
      UnitDef(id: 'miles_per_us_gallon', name: 'Miles per US Gallon', symbol: 'mpg (US)', strategy: UnitStrategy.factor, factor: 0.425144),
      UnitDef(id: 'miles_per_imperial_gallon', name: 'Miles per Imperial Gallon', symbol: 'mpg (UK)', strategy: UnitStrategy.factor, factor: 0.354006),
    ]),
    CategoryDef(id: 'pressure', name: 'Pressure', isStringBased: false, units: [
      UnitDef(id: 'atmosphere', name: 'Atmosphere', symbol: 'atm', strategy: UnitStrategy.factor, factor: 101325.0),
      UnitDef(id: 'bar', name: 'Bar', symbol: 'bar', strategy: UnitStrategy.factor, factor: 100000.0),
      UnitDef(id: 'millibar', name: 'Millibar', symbol: 'mbar', strategy: UnitStrategy.factor, factor: 100.0),
      UnitDef(id: 'psi', name: 'Pound per Square Inch', symbol: 'psi', strategy: UnitStrategy.factor, factor: 6894.76),
      UnitDef(id: 'pascal', name: 'Pascal', symbol: 'Pa', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'kilo_pascal', name: 'Kilopascal', symbol: 'kPa', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'torr', name: 'Torr', symbol: 'Torr', strategy: UnitStrategy.factor, factor: 133.322),
      UnitDef(id: 'inch_of_mercury', name: 'Inch of Mercury', symbol: 'inHg', strategy: UnitStrategy.factor, factor: 3386.39),
      UnitDef(id: 'hecto_pascal', name: 'Hectopascal', symbol: 'hPa', strategy: UnitStrategy.factor, factor: 100.0),
      UnitDef(id: 'ksi', name: 'Kilopound per Square Inch', symbol: 'ksi', strategy: UnitStrategy.factor, factor: 6894757.2932),
      UnitDef(id: 'mega_pascal', name: 'Megapascal', symbol: 'MPa', strategy: UnitStrategy.factor, factor: 1000000.0),
      UnitDef(id: 'giga_pascal', name: 'Gigapascal', symbol: 'GPa', strategy: UnitStrategy.factor, factor: 1000000000.0),
    ]),
    CategoryDef(id: 'energy', name: 'Energy', isStringBased: false, units: [
      UnitDef(id: 'kilowatt_hours', name: 'Kilowatt-hours', symbol: 'kWh', strategy: UnitStrategy.factor, factor: 3600000.0),
      UnitDef(id: 'watt_hours', name: 'Watt-hours', symbol: 'Wh', strategy: UnitStrategy.factor, factor: 3600.0),
      UnitDef(id: 'kilocalories', name: 'Kilocalories', symbol: 'kcal', strategy: UnitStrategy.factor, factor: 4184.0),
      UnitDef(id: 'calories', name: 'Calories', symbol: 'cal', strategy: UnitStrategy.factor, factor: 4.184),
      UnitDef(id: 'joules', name: 'Joules', symbol: 'J', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'kilojoules', name: 'Kilojoules', symbol: 'kJ', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'electronvolts', name: 'Electronvolts', symbol: 'eV', strategy: UnitStrategy.factor, factor: 1.602176565e-19),
      UnitDef(id: 'energy_foot_pound', name: 'Foot-pound', symbol: 'ft·lbf', strategy: UnitStrategy.factor, factor: 1.35582),
      UnitDef(id: 'british_thermal_unit', name: 'British Thermal Unit', symbol: 'BTU', strategy: UnitStrategy.factor, factor: 1055.06),
    ]),
    CategoryDef(id: 'power', name: 'Power', isStringBased: false, units: [
      UnitDef(id: 'kilowatt', name: 'Kilowatt', symbol: 'kW', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'european_horse_power', name: 'Metric Horsepower', symbol: 'hp (met)', strategy: UnitStrategy.factor, factor: 735.49875),
      UnitDef(id: 'imperial_horse_power', name: 'Imperial Horsepower', symbol: 'hp (imp)', strategy: UnitStrategy.factor, factor: 745.7),
      UnitDef(id: 'watt', name: 'Watt', symbol: 'W', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'megawatt', name: 'Megawatt', symbol: 'MW', strategy: UnitStrategy.factor, factor: 1000000.0),
      UnitDef(id: 'gigawatt', name: 'Gigawatt', symbol: 'GW', strategy: UnitStrategy.factor, factor: 1000000000.0),
      UnitDef(id: 'milliwatt', name: 'Milliwatt', symbol: 'mW', strategy: UnitStrategy.factor, factor: 0.001),
    ]),
    CategoryDef(id: 'angle', name: 'Angle', isStringBased: false, units: [
      UnitDef(id: 'degree', name: 'Degree', symbol: '°', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'radians', name: 'Radians', symbol: 'rad', strategy: UnitStrategy.factor, factor: 57.295779513),
      UnitDef(id: 'minutes_angle', name: 'Minutes', symbol: "'", strategy: UnitStrategy.factor, factor: 0.0166667),
      UnitDef(id: 'seconds_angle', name: 'Seconds', symbol: '"', strategy: UnitStrategy.factor, factor: 0.000277778),
    ]),
    CategoryDef(id: 'torque', name: 'Torque', isStringBased: false, units: [
      UnitDef(id: 'newton_meter', name: 'Newton-meter', symbol: 'N·m', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'kilogram_force_meter', name: 'Kilogram-force meter', symbol: 'kgf·m', strategy: UnitStrategy.factor, factor: 9.80665),
      UnitDef(id: 'dyne_meter', name: 'Dyne-meter', symbol: 'dyn·m', strategy: UnitStrategy.factor, factor: 1e-5),
      UnitDef(id: 'pound_force_feet', name: 'Pound-force feet', symbol: 'lbf·ft', strategy: UnitStrategy.factor, factor: 1.35582),
      UnitDef(id: 'pound_force_inch', name: 'Pound-force inch', symbol: 'lbf·in', strategy: UnitStrategy.factor, factor: 0.112984829),
      UnitDef(id: 'poundal_meter', name: 'Poundal meter', symbol: 'pdl·m', strategy: UnitStrategy.factor, factor: 0.138255),
    ]),
    CategoryDef(id: 'digital_data', name: 'Digital Data', isStringBased: false, units: [
      UnitDef(id: 'byte', name: 'Byte', symbol: 'B', strategy: UnitStrategy.factor, factor: 8.0),
      UnitDef(id: 'bit', name: 'Bit', symbol: 'b', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'nibble', name: 'Nibble', symbol: 'nib', strategy: UnitStrategy.factor, factor: 4.0),
      UnitDef(id: 'kilobyte', name: 'Kilobyte (10³)', symbol: 'KB', strategy: UnitStrategy.factor, factor: 8000.0),
      UnitDef(id: 'megabyte', name: 'Megabyte (10⁶)', symbol: 'MB', strategy: UnitStrategy.factor, factor: 8000000.0),
      UnitDef(id: 'gigabyte', name: 'Gigabyte (10⁹)', symbol: 'GB', strategy: UnitStrategy.factor, factor: 8e9),
      UnitDef(id: 'terabyte', name: 'Terabyte (10¹²)', symbol: 'TB', strategy: UnitStrategy.factor, factor: 8e12),
      UnitDef(id: 'petabyte', name: 'Petabyte (10¹⁵)', symbol: 'PB', strategy: UnitStrategy.factor, factor: 8e15),
      UnitDef(id: 'exabyte', name: 'Exabyte (10¹⁸)', symbol: 'EB', strategy: UnitStrategy.factor, factor: 8e18),
      UnitDef(id: 'kibibyte', name: 'Kibibyte (2¹⁰)', symbol: 'KiB', strategy: UnitStrategy.factor, factor: 8192.0),
      UnitDef(id: 'mebibyte', name: 'Mebibyte (2²⁰)', symbol: 'MiB', strategy: UnitStrategy.factor, factor: 8388608.0),
      UnitDef(id: 'gibibyte', name: 'Gibibyte (2³⁰)', symbol: 'GiB', strategy: UnitStrategy.factor, factor: 8589934592.0),
      UnitDef(id: 'tebibyte', name: 'Tebibyte (2⁴⁰)', symbol: 'TiB', strategy: UnitStrategy.factor, factor: 8796093022208.0),
      UnitDef(id: 'pebibyte', name: 'Pebibyte (2⁵⁰)', symbol: 'PiB', strategy: UnitStrategy.factor, factor: 9007199254740992.0),
      UnitDef(id: 'exbibyte', name: 'Exbibyte (2⁶⁰)', symbol: 'EiB', strategy: UnitStrategy.factor, factor: 9223372036854775808.0),
      UnitDef(id: 'kilobit', name: 'Kilobit (10³)', symbol: 'kb', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'megabit', name: 'Megabit (10⁶)', symbol: 'Mb', strategy: UnitStrategy.factor, factor: 1e6),
      UnitDef(id: 'gigabit', name: 'Gigabit (10⁹)', symbol: 'Gb', strategy: UnitStrategy.factor, factor: 1e9),
      UnitDef(id: 'terabit', name: 'Terabit (10¹²)', symbol: 'Tb', strategy: UnitStrategy.factor, factor: 1e12),
      UnitDef(id: 'petabit', name: 'Petabit (10¹⁵)', symbol: 'Pb', strategy: UnitStrategy.factor, factor: 1e15),
      UnitDef(id: 'exabit', name: 'Exabit (10¹⁸)', symbol: 'Eb', strategy: UnitStrategy.factor, factor: 1e18),
      UnitDef(id: 'kibibit', name: 'Kibibit (2¹⁰)', symbol: 'Kib', strategy: UnitStrategy.factor, factor: 1024.0),
      UnitDef(id: 'mebibit', name: 'Mebibit (2²⁰)', symbol: 'Mib', strategy: UnitStrategy.factor, factor: 1048576.0),
      UnitDef(id: 'gibibit', name: 'Gibibit (2³⁰)', symbol: 'Gib', strategy: UnitStrategy.factor, factor: 1073741824.0),
      UnitDef(id: 'tebibit', name: 'Tebibit (2⁴⁰)', symbol: 'Tib', strategy: UnitStrategy.factor, factor: 1099511627776.0),
      UnitDef(id: 'pebibit', name: 'Pebibit (2⁵⁰)', symbol: 'Pib', strategy: UnitStrategy.factor, factor: 1125899906842624.0),
      UnitDef(id: 'exbibit', name: 'Exbibit (2⁶⁰)', symbol: 'Eib', strategy: UnitStrategy.factor, factor: 1152921504606846976.0),
    ]),
    CategoryDef(id: 'si_prefixes', name: 'SI Prefixes', isStringBased: false, units: [
      UnitDef(id: 'base', name: 'Base (1)', symbol: '', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'deca', name: 'Deca (10)', symbol: 'da', strategy: UnitStrategy.factor, factor: 10.0),
      UnitDef(id: 'hecto', name: 'Hecto (10²)', symbol: 'h', strategy: UnitStrategy.factor, factor: 100.0),
      UnitDef(id: 'kilo', name: 'Kilo (10³)', symbol: 'k', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'mega', name: 'Mega (10⁶)', symbol: 'M', strategy: UnitStrategy.factor, factor: 1e6),
      UnitDef(id: 'giga', name: 'Giga (10⁹)', symbol: 'G', strategy: UnitStrategy.factor, factor: 1e9),
      UnitDef(id: 'tera', name: 'Tera (10¹²)', symbol: 'T', strategy: UnitStrategy.factor, factor: 1e12),
      UnitDef(id: 'peta', name: 'Peta (10¹⁵)', symbol: 'P', strategy: UnitStrategy.factor, factor: 1e15),
      UnitDef(id: 'exa', name: 'Exa (10¹⁸)', symbol: 'E', strategy: UnitStrategy.factor, factor: 1e18),
      UnitDef(id: 'zetta', name: 'Zetta (10²¹)', symbol: 'Z', strategy: UnitStrategy.factor, factor: 1e21),
      UnitDef(id: 'yotta', name: 'Yotta (10²⁴)', symbol: 'Y', strategy: UnitStrategy.factor, factor: 1e24),
      UnitDef(id: 'deci', name: 'Deci (10⁻¹)', symbol: 'd', strategy: UnitStrategy.factor, factor: 0.1),
      UnitDef(id: 'centi', name: 'Centi (10⁻²)', symbol: 'c', strategy: UnitStrategy.factor, factor: 0.01),
      UnitDef(id: 'milli', name: 'Milli (10⁻³)', symbol: 'm', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'micro', name: 'Micro (10⁻⁶)', symbol: 'µ', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'nano', name: 'Nano (10⁻⁹)', symbol: 'n', strategy: UnitStrategy.factor, factor: 1e-9),
      UnitDef(id: 'pico', name: 'Pico (10⁻¹²)', symbol: 'p', strategy: UnitStrategy.factor, factor: 1e-12),
      UnitDef(id: 'femto', name: 'Femto (10⁻¹⁵)', symbol: 'f', strategy: UnitStrategy.factor, factor: 1e-15),
      UnitDef(id: 'atto', name: 'Atto (10⁻¹⁸)', symbol: 'a', strategy: UnitStrategy.factor, factor: 1e-18),
      UnitDef(id: 'zepto', name: 'Zepto (10⁻²¹)', symbol: 'z', strategy: UnitStrategy.factor, factor: 1e-21),
      UnitDef(id: 'yocto', name: 'Yocto (10⁻²⁴)', symbol: 'y', strategy: UnitStrategy.factor, factor: 1e-24),
    ]),
    CategoryDef(id: 'density', name: 'Density', isStringBased: false, units: [
      UnitDef(id: 'grams_per_liter', name: 'Grams per Liter', symbol: 'g/L', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'grams_per_cubic_centimeter', name: 'Grams per Cubic Centimeter', symbol: 'g/cm³', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'grams_per_milliliter', name: 'Grams per Milliliter', symbol: 'g/mL', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'grams_per_deciliter', name: 'Grams per Deciliter', symbol: 'g/dL', strategy: UnitStrategy.factor, factor: 10.0),
      UnitDef(id: 'kilograms_per_liter', name: 'Kilograms per Liter', symbol: 'kg/L', strategy: UnitStrategy.factor, factor: 1000.0),
      UnitDef(id: 'kilograms_per_cubic_meter', name: 'Kilograms per Cubic Meter', symbol: 'kg/m³', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'milligrams_per_liter', name: 'Milligrams per Liter', symbol: 'mg/L', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'milligrams_per_deciliter', name: 'Milligrams per Deciliter', symbol: 'mg/dL', strategy: UnitStrategy.factor, factor: 0.01),
      UnitDef(id: 'milligrams_per_milliliter', name: 'Milligrams per Milliliter', symbol: 'mg/mL', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'milligrams_per_cubic_meter', name: 'Milligrams per Cubic Meter', symbol: 'mg/m³', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'milligrams_per_cubic_centimeter', name: 'Milligrams per Cubic Centimeter', symbol: 'mg/cm³', strategy: UnitStrategy.factor, factor: 1.0),
      UnitDef(id: 'micrograms_per_liter', name: 'Micrograms per Liter', symbol: 'µg/L', strategy: UnitStrategy.factor, factor: 1e-6),
      UnitDef(id: 'micrograms_per_deciliter', name: 'Micrograms per Deciliter', symbol: 'µg/dL', strategy: UnitStrategy.factor, factor: 1e-5),
      UnitDef(id: 'micrograms_per_milliliter', name: 'Micrograms per Milliliter', symbol: 'µg/mL', strategy: UnitStrategy.factor, factor: 0.001),
      UnitDef(id: 'pounds_per_cubic_inches', name: 'Pounds per Cubic Inch', symbol: 'lb/in³', strategy: UnitStrategy.factor, factor: 17218.03),
      UnitDef(id: 'pounds_per_cubic_feet', name: 'Pounds per Cubic Foot', symbol: 'lb/ft³', strategy: UnitStrategy.factor, factor: 0.453592 * 35.3147),
    ]),
    CategoryDef(id: 'temperature', name: 'Temperature', isStringBased: false, units: [
      UnitDef(id: 'celsius', name: 'Celsius', symbol: '°C', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'fahrenheit', name: 'Fahrenheit', symbol: '°F', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'kelvin', name: 'Kelvin', symbol: 'K', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'reamur', name: 'Réaumur', symbol: '°Re', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'romer', name: 'Rømer', symbol: '°Rø', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'delisle', name: 'Delisle', symbol: '°De', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'rankine', name: 'Rankine', symbol: '°Ra', strategy: UnitStrategy.formula, factor: 1.0),
    ]),
    CategoryDef(id: 'numeral_systems', name: 'Numeral Systems', isStringBased: true, units: [
      UnitDef(id: 'binary', name: 'Binary', symbol: 'base 2', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'octal', name: 'Octal', symbol: 'base 8', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'decimal_numeral', name: 'Decimal', symbol: 'base 10', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'hexadecimal', name: 'Hexadecimal', symbol: 'base 16', strategy: UnitStrategy.formula, factor: 1.0),
    ]),
    CategoryDef(id: 'shoe_size', name: 'Shoe Size', isStringBased: false, units: [
      UnitDef(id: 'centimeters', name: 'Centimeters', symbol: 'cm', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'inches_shoe', name: 'Inches', symbol: 'in', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'eu_china', name: 'EU / China', symbol: 'EU', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'usa_canada_man', name: 'US/Canada Men', symbol: 'US M', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'usa_canada_woman', name: 'US/Canada Women', symbol: 'US W', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'usa_canada_child', name: 'US/Canada Child', symbol: 'US C', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'uk_india_man', name: 'UK/India Men', symbol: 'UK M', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'uk_india_woman', name: 'UK/India Women', symbol: 'UK W', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'uk_india_child', name: 'UK/India Child', symbol: 'UK C', strategy: UnitStrategy.formula, factor: 1.0),
      UnitDef(id: 'japan', name: 'Japan', symbol: 'JP', strategy: UnitStrategy.formula, factor: 1.0),
    ]),
  ];
  static CategoryDef? byId(String id) { for (final c in categories) { if (c.id == id) return c; } return null; }
}
